/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algo5;

import Algo5.cli.CommandLineInterface;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        CommandLineInterface.run();
    }
}
